# Use an official base image as a starting point
FROM ubuntu:latest
# Create a non-root user "ivan_rodri" with UID 1000
RUN useradd -u 1000 -m -s /bin/bash ivan_rodri

# Set the working directory to the user's home directory
WORKDIR /home/ivan_rodri

# Switch to the newly created user
USER ivan_rodri